# Generated by Django 4.2.7 on 2025-08-06 06:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricealert',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.store'),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='threshold_percent',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Percentage change threshold to trigger alert', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
