# Generated by Django 5.1.2 on 2025-08-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_store_address_store_latitude_store_longitude'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='store',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='store',
            name='store_code',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='store',
            name='chain',
            field=models.CharField(choices=[('paknsave', "Pak'nSave"), ('countdown', 'Woolworths'), ('new_world', 'New World')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='store',
            unique_together={('name', 'chain', 'city')},
        ),
    ]
