# Generated by Django 5.1.2 on 2025-08-14 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_store_unique_together_store_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gtin',
            field=models.CharField(blank=True, help_text='Global Trade Item Number (8, 12, 13, or 14 digits)', max_length=14, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('OFF', 'Open Food Facts'), ('GS1', 'GS1 NZ')], max_length=3)),
                ('file', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('url', models.URLField(blank=True, max_length=500)),
                ('last_fetched_at', models.DateTimeField(auto_now_add=True)),
                ('attribution_text', models.CharField(blank=True, max_length=200)),
                ('attribution_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('checksum', models.CharField(blank=True, help_text='MD5 hash of image content', max_length=32)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_assets', to='api.product')),
            ],
            options={
                'ordering': ['-last_fetched_at'],
                'unique_together': {('product', 'source', 'checksum')},
            },
        ),
    ]
