# Generated by Django 5.1.2 on 2025-08-22 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_gtin_imageasset'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imageasset',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='imageasset',
            name='file_size',
            field=models.IntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='imageasset',
            name='original_url',
            field=models.URLField(blank=True, help_text='Original URL where image was found', max_length=500),
        ),
        migrations.AddField(
            model_name='imageasset',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='api.store'),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='source',
            field=models.CharField(choices=[('OFF', 'Open Food Facts'), ('GS1', 'GS1 NZ'), ('STORE', 'Store Website')], max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='imageasset',
            unique_together={('product', 'store', 'source', 'checksum')},
        ),
    ]
