# Generated by Django 5.1.2 on 2025-08-22 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_imageasset_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageasset',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alt text for accessibility', max_length=200),
        ),
        migrations.AddField(
            model_name='imageasset',
            name='sku',
            field=models.CharField(blank=True, help_text='SKU or identifier for the image', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_assets', to='api.product'),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='source',
            field=models.CharField(choices=[('OFF', 'Open Food Facts'), ('GS1', 'GS1 NZ'), ('STORE', 'Store Website'), ('UPLOAD', 'User Upload')], default='UPLOAD', max_length=10),
        ),
    ]
