# Generated by Django 4.2.7 on 2025-08-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_imageasset_alt_text_imageasset_sku_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('origin', models.CharField(max_length=100)),
                ('allergens', models.JSONField(default=list)),
                ('claims', models.JSONField(default=list)),
                ('storage', models.TextField()),
                ('warnings', models.JSONField(default=list)),
                ('serving_g', models.IntegerField()),
                ('energy_kj', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fat_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sat_fat_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carbs_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sugars_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('protein_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sodium_mg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('last_verified_at', models.DateTimeField()),
                ('source', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
