# Generated by Django 5.1.2 on 2025-09-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_product_image'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='store',
            constraint=models.CheckConstraint(condition=models.Q(('chain__in', ['paknsave', 'countdown', 'new_world'])), name='store_chain_valid'),
        ),
    ]
